apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bacula-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bacula-exporter.name" . }}
    helm.sh/chart: {{ include "bacula-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.labels -}}
    {{- .Values.labels | toYaml | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  bacula_exporter.knf: |
    [http]
      ip: {{ .Values.baculaExporter.http.ip }}
      port: {{ .Values.baculaExporter.http.port }}
      endpoint: {{ .Values.baculaExporter.http.endpoint }}

    [db]
      name: {{ .Values.baculaExporter.db.name }}
      username: {{ .Values.baculaExporter.db.username }}
      password: {{ .Values.baculaExporter.db.password }}
      host: {{ .Values.baculaExporter.db.host }}
      port: {{ .Values.baculaExporter.db.port }}
      sslmode: {{ .Values.baculaExporter.db.sslmode }}

    [log]
      output: {{ .Values.baculaExporter.log.output }}
      dir: {{ .Values.baculaExporter.log.dir }}
      file: {log:dir}/bacula_exporter.log
      perms: {{ .Values.baculaExporter.log.perms }}
      level: {{ .Values.baculaExporter.log.level }}
