apiVersion: v1
kind: Service
metadata:
  name: {{ include "bacula-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bacula-exporter.name" . }}
    helm.sh/chart: {{ include "bacula-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.labels -}}
    {{ .Values.labels | toYaml | nindent 4 -}}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "bacula-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
