apiVersion: v1
appVersion: "1.0.1"
description: Helm chart bacula_exporter for Kubernetes
name: bacula-exporter
version: 1.0.0
home: https://github.com/funbox/bacula_exporter
maintainers:
  - name: Gleb Goncharov
    email: g.goncharov@fun-box.ru
